### ISSUE TITLE
Validar estabelecimento de sessão de mídia com NAT

### ISSUE THREAD

**Issue by DouglasAmorim** [Douglas-and-Adonis/jogo-web-rtc#18]
Garantir que a mídia trafegará entre os dois clientes mesmo com NAT em um dos terminais.

Depende de #17.

**Comment by DouglasAmorim** [comment]
Link do video no YouTube: https://www.youtube.com/watch?v=BCJKL1AuGDY

**Comment by boidacarapreta** [comment]
O cenário vai funcionar apenas em rede sem problemas de NAT, pois o uso de STUN/TURN/ICE não está funcionando.

Para corrigir, é preciso mudar no arquivo `cliente.js` o valor do objeto, de `ice_servers` para `iceServers`:

```diff
douglas.as1997@TELE-SMU:~/jogo-web-rtc$ git diff
diff --git a/client.js b/client.js
index d9a4281..c8d1e18 100644
--- a/client.js
+++ b/client.js
@@ -27,7 +27,7 @@ var info = 0
 const peerConnections = {};
 
 const iceServers = {
-  ice_servers: [
+  iceServers: [
     { urls: "stun:smu20211.sj.ifsc.edu.br" },
     {
       urls: "turn:smu20211.sj.ifsc.edu.br",
```
